{% set name = "nlp" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0aa6bc966ffc2d2be7248bd71f258360281cd717c10811e1b55bb2fa50bf79d4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
  run:
    - dill
    - filelock
    - numpy
    - pyarrow ==0.17.1
    - python
    - requests >=2.19.0
    - tqdm >=4.27
    - dataclasses  # [py36]

test:
  imports:
    - nlp
    - nlp.commands
    - nlp.datasets
    - nlp.metrics
    - nlp.utils

about:
  home: https://github.com/huggingface/nlp
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: HuggingFace/NLP is an open library of NLP datasets.
  doc_url: https://huggingface.co/nlp/
  dev_url: https://github.com/huggingface/nlp

extra:
  recipe-maintainers:
    - ndmaxar
    - oblute
    - rluria14
